name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  packages: write

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.19.8'

      - uses: pnpm/action-setup@v4
        with:
          version: '8.3.0'
      - uses: actions/setup-node@v4
        with:
          node-version: '16.18.1'
          cache: pnpm

      - name: Run pre-build
        working-directory: ./cmd/server/
        run: ./pre-build.sh
      - name: Run build
        working-directory: ./cmd/server/
        env:
          IMAGE: ghcr.io/pitkley/gatherstack:latest
          VERSION: 5.1.0
        run: ./build.sh

      - name: Login to ghcr.io
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Push built image
        if: github.ref == 'refs/heads/main'
        run: docker image push ghcr.io/pitkley/gatherstack:latest
