name: Licenses Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.19.8'
      - uses: ruby/setup-ruby@v1

      - uses: pnpm/action-setup@v4
        with:
          version: '8.3.0'
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '16.18.1'
          cache: pnpm

#      - name: Get pnpm store directory
#        id: pnpm-cache
#        shell: bash
#        run: |
#          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
#      - uses: actions/cache@v3
#        name: Setup pnpm cache
#        with:
#          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
#          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
#          restore-keys: |
#            ${{ runner.os }}-pnpm-store-

      - name: Install license_finder
        run: gem install license_finder:7.1.0 # sync with licenses-update.yml

      - name: Check dependencies
        run: LICENSE_CHECK=true ./dev/licenses.sh
